import * as fs from 'fs';
import * as path from 'path';
import { app } from 'electron';
import { execFile } from 'child_process';
import { promisify } from 'util';

const execFileAsync = promisify(execFile);

export class CertificateManager {
  private certsDir: string;

  constructor(customDir?: string) {
    this.certsDir = customDir || path.join(app.getPath('userData'), 'certs');
    if (!fs.existsSync(this.certsDir)) {
      fs.mkdirSync(this.certsDir, { recursive: true });
    }
  }

  async initialize(): Promise<void> {
    // http-mitm-proxy auto-generates its own CA in sslCaDir/certs/ca.pem
    // We just ensure the directory exists
  }

  /** Path to the CA cert generated by http-mitm-proxy */
  getCaCertPath(): string {
    return path.join(this.certsDir, 'certs', 'ca.pem');
  }

  getSslCaDir(): string {
    return this.certsDir;
  }

  /** Check if the CA cert file exists (created after first proxy start) */
  hasCaCert(): boolean {
    return fs.existsSync(this.getCaCertPath());
  }

  /** Install the CA cert into the Windows Current User trusted root store */
  async installCaCertWindows(): Promise<{ success: boolean; message: string }> {
    const certPath = this.getCaCertPath();
    if (!fs.existsSync(certPath)) {
      return { success: false, message: 'CA certificate not found. Start the proxy first to generate it.' };
    }

    try {
      await execFileAsync('certutil', ['-addstore', '-user', 'Root', certPath]);
      return { success: true, message: 'ProxyBoy CA certificate installed successfully.' };
    } catch (error: any) {
      // User cancelled the security dialog or other error
      if (error.code === 'ERR_CHILD_PROCESS_STDIO_MAXBUFFER' || error.stderr?.includes('cancelled')) {
        return { success: false, message: 'Certificate installation was cancelled.' };
      }
      return { success: false, message: `Failed to install certificate: ${error.message}` };
    }
  }

  /** Check if the CA cert is already in the Windows trusted root store */
  async isCaCertInstalled(): Promise<boolean> {
    try {
      const { stdout } = await execFileAsync('certutil', ['-verifystore', '-user', 'Root', 'ProxyBoy CA']);
      return stdout.includes('ProxyBoy') || stdout.includes('command completed successfully');
    } catch {
      return false;
    }
  }
}
